name: Generate Release
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "VersionName ex.) 1.0.0"
        type: string
      message:
        description: 'Deploy Message'
        required: true
        type: string

jobs:
  generate_release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Generate Tag
        id: tag
        run: |
          CURRENT_DATE=$(date +"%Y년%m월%d일_%H시%M분")
          echo "val=$CURRENT_DATE" >> "$GITHUB_OUTPUT"

      - name: Generate Release
        uses: ncipollo/release-action@v1.14.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ steps.tag.outputs.val }}
          name: Release ${{ inputs.version }}
          body: |
            ## Changes
            ${{ inputs.message }}
