name: Generate Release
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
      message:
        description: 'Deploy Message'
        required: true
        type: string

jobs:
  generate_release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Generate Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: ${{ inputs.version }}
          tag_name: ${{ inputs.version }}
          body: |
                ${{ inputs.message }}
          draft: false
          prerelease: false
