name: Generate Release
on:
  workflow_dispatch:
    inputs:
      versionCode:
        required: true
        description: "VersionCode ex.) 1"
        type: string
      version:
        required: true
        description: "VersionName ex.) 1.0.0"
        type: string
      message:
        description: 'Deploy Message'
        required: true
        type: string

jobs:
  generate_release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
          
      - name: Generate Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: $(date + "%Y년_%m월_%d일-%H시%분")
          release_name: Release ${{ inputs.version }}
          body: |
            ## Changes
            ${{ inputs.message }}
          draft: false
          release: false
